import QRCodeClient from "@/components/room/QRCodeClient";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "GameRoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <QRCodeClient />
      </body>
    </html>
  );
}
